<?xml version="1.0" encoding="utf-8"?><Database Name="HappinessMetric" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.10.198;Initial Catalog=HappinessMetric;Persist Security Info=True;User ID=HappinessMetric" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HappinessMetricConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HappinessRating" Member="HappinessRatings">
    <Type Name="HappinessRating">
      <Column Name="RatingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Sprint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Developer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HappyRatingwithTeam" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="FeelsBest" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="FeelsWorst" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="IncreaseHappiness" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project_Sprint_Details" Member="Project_Sprint_Details">
    <Type Name="Project_Sprint_Detail">
      <Column Name="ps_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ps_projectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ps_sprintNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ps_sprintStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ps_sprintDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="pj_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pj_name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pj_description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="pj_parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pj_isactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pj_createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="us_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="us_username" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="us_firstname" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="us_lastname" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="us_email" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="us_isadmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="us_isactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="us_createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Project_User_Junc" Member="Project_User_Juncs">
    <Type Name="Project_User_Junc">
      <Column Name="pu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pu_projectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pu_userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pu_isadmin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pu_isactive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pu_createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>